### ISSUE TITLE
Nested `.optional()` fields inside `.partial()` generate `v.any()` instead of preserving type

### ISSUE THREAD

**Issue by dpkass** [panzacoder/zodvex#16]
When using Zod with Convex, nested optional fields inside an object are not preserved correctly if the parent object is wrapped with `.partial()`. Instead of producing `v.optional(v.number())`, Convex generates `v.any()` for those fields. This causes validation failures even though the TypeScript types are correct.

## Example

```ts
import { z } from "zod";

const Experience = z.object({
  min: z.number().optional(),
  max: z.number().optional(),
});

const Live = z.object({
  status: z.literal("live"),
  experience: Experience,
});

export const Draft = Live.partial().extend({
  status: z.literal("draft"),
});

export const TestSchema = z.union([Live, Draft]);

// schema.ts
export default defineSchema({
  test: defineTable(zodToConvex(TestSchema)),
});

// convex/test.ts
export const mutate = zMutation({
  args: { data: TestSchema },
  handler: async (ctx, { data }) => {
    console.log(data);
  },
});
```

## Expected

Draft should validate with an empty `experience` object:

```ts
data: {
  status: "draft",
  experience: {}, // should be valid
}
```

Validator should look like:

```ts
v.union(
  v.object({
    status: v.literal("live"),
    experience: v.object({
      min: v.optional(v.float64()),
      max: v.optional(v.float64()),
    }),
  }),
  v.object({
    status: v.literal("draft"),
    experience: v.optional(
      v.object({
        min: v.optional(v.float64()),
        max: v.optional(v.float64()),
      })
    ),
  })
);
```

## Actual

Convex generates:

```ts
v.union(
  v.object({
    status: v.literal("live"),
    experience: v.object({
      min: v.optional(v.float64()),
      max: v.optional(v.float64()),
    }),
  }),
  v.object({
    status: v.literal("draft"),
    experience: v.optional(
      v.object({
        min: v.any(),
        max: v.any(),
      })
    ),
  })
);
```

This makes the following **fail (`ArgumentValidationError`)** at runtime, even though the TS type accepts it:

```ts
muatate({
  data: {
    status: "draft",
    experience: {},
  },
});
```

Meanwhile, the live case **succeeds**:

```ts
muatate({
  data: {
    status: "live",
    experience: {},
  },
});
```

## Note
The generated TypeScript types are **correct**:

```ts
data:
  | {
      status: "live";
      experience: { min?: number; max?: number };
    }
  | {
      status: "draft";
      experience?: { min?: number; max?: number };
    }
```

…but the runtime validator disagrees, due to `v.any()` replacing the inner optionals.

**Comment by panzacoder** [comment]
Hi @dpkass! I've fixed this bug in PR #XX. You can test the fix by installing directly from the branch:

` npm install panzacoder/zodvex#fix/union-mapping-with-partials`
> Notes: This will run `tsup` which may take a moment. If it hangs just try installing again. If you have issues with this please let me know.

Let me know if this resolves your issue!

**Comment by dpkass** [comment]
I temporarily switched to `import {...} from "zodvex/src"` and then it worked.
Everything resolved on my side. Thank you very much for your reaction speed!

**Comment by dpkass** [comment]
Nope, sadly still not working. I tried out both PnP and node_modules and I still get can't resolve module:

```js
Import trace for requested module:
./src/app/job-postings/(form)/components/schema.ts
./src/app/job-postings/(form)/components/create-jobposting-form/index.tsx
 ⨯ ./src/lib/contracts/jobPostingSchema.ts:2:1
Module not found: Can't resolve 'zodvex'
  1 | import { z } from "zod";
> 2 | import { zid } from "zodvex";
    | ^
  3 |
  4 | export const JobPostingStatus = z.enum([
  5 |   "draft",
```
